before_script:
  - ruby -v
  - bundle install
  # - pwd
  - cp config/database.example.yml config/database.yml
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails db:seed RAILS_ENV=test

stages:
  - test
  - deploy

rspec:
  stage: test
  variables:
    # CI_DEBUG_TRACE: "true"
  script:
    - bundle exec rspec spec -fd

deploy:
  stage: deploy
  script:
    - bundle exec mina dev deploy
