root_url: 'http://gesanghua.wikiflyer.cn/'
app_host: 'gesanghua.wikiflyer.cn'
app_name: '格桑花项目'
app_desc: '格桑花项目'
logo_img: ''

# 短信设置
send_sms: true

# 开发模式
development_mode: false

# 配置学费
junior_term_amount: 1050
junior_year_amount: 2100
senior_term_amount: 1050
senior_year_amount: 2100

# 微信公众号
wechat_app_id: "wx7187f48a03d4d947"
wechat_app_secret: "e3ff7c50f865535ab1eef7ea55b6c0c1"
wechat_app_token: "3147d1cea898763a7f677b3c"

# 微信支付
wechat_mch_id: "1386171602"
wechat_pay_key: "34894D77893800F28FD98B6EDD34FFE2"

children_template_file_path: '/files/受益学生名单模板.xlsx'

# 默认金额卡片
amount_tabs: [500, 1000, 1500, 2000]
