root_url: 'http://gesanghua.wikiflyer.cn/'
app_host: 'gesanghua.wikiflyer.cn'
app_name: '格桑花项目'
app_desc: '格桑花项目'
logo_img: ''

# 短信设置
send_sms: true

# 开发模式
development_mode: false

# 配置学费
junior_term_amount: 1050
junior_year_amount: 2100
senior_term_amount: 1050
senior_year_amount: 2100

# 微信公众号
wechat_app_id: "wx771c54fb737861a3"
wechat_app_secret: "7faa87ee5c43e2f0ff5465459e34a264"
wechat_app_token: "c06a2a40256fdeb47ff0c7cc"

# 微信支付
wechat_mch_id: "1386171602"
wechat_pay_key: "34894D77893800F28FD98B6EDD34FFE2"
