root_url: 'http://gesanghua.wikiflyer.cn/'
app_host: 'gesanghua.wikiflyer.cn'
m_root_url: 'http://gesanghua.wikiflyer.cn/m'
app_name: '格桑花'
app_desc: '格桑花'
logo_img: ''

# 短信设置
send_sms: false

# 开发模式
development_mode: false

# 跳过支付模式
skip_pay_mode: false

# 支付1分钱模式
pay_1_mode: true

# 接口调试默认使用用户, 禁用设置false，启用设置用户id
api_defautl_user: false

# 配置学费
junior_term_amount: 1050
junior_year_amount: 2100
senior_term_amount: 1050
senior_year_amount: 2100

# 微信公众号
wechat_app_id: "wx771c54fb737861a3"
wechat_app_secret: "727a1fe9d8216c3ba8bfb21be61ec6bd"
wechat_app_token: "3147d1cea898763a7f677b3c"

# 微信开放平台
wechat_open_id: "wxe41f15aeaef1c627"
wechat_open_secret: "2b45ea0694762f2418f0e9a1e01072c4"
wechat_open_token: "3147d1cea898763a7f677b3c"

# 微信支付
wechat_mch_id: "1386171602"
wechat_pay_key: "34894D77893800F28FD98B6EDD34FFE2"

children_template_file_path: '/files/受益学生名单模板.xlsx'

# 默认金额卡片
amount_tabs: [500, 1000, 1500, 2000]

# 支付宝
alipay_app_id: '2016091100487099'
alipay_app_private_key: "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA1/L/H7B3bH/ZYg7Fagr0VO5kSyNEYCn6a6sAQgE6o2Ezgfzw\n8btPxUCvTbBH7zlY0/dheZbhHVgEk3hZKm38yXlZjiSNXzyUAkVn50wgGPcH+0qc\nAa04XQ2i2eh4cpxtuVX2kEw9w4zetkWe7diQonPJbcwyAu5MnjwOQBVSODyPNX6p\nOePTC24iphyGKc2Bm3gB9xYkPaKMoWXl/NHIHYMQ3JRDMXwAXT6fjIBEdlm5sK7R\nVxcbreaCsTpD1l/lfji7UV5rR+J29NFP6zzsyqW8sViMWAiT7qDnnxvXy8AFKE8i\nbg8EI1YKktp4UYaEeU4qR6n6EvgXJd70QzaSaQIDAQABAoIBAHLgSkViS3VFYa+f\nKfdqUmWn12R9I0+ApT2HXwC9xKLK/2qD0uzU9u94pIjQYMPqns1LiOf0klZYzz5f\nxBclIVdQHYrW+PmTsSywHUDWpzCAoRdVrj3aFuSxb1M6LnDRtDDmgN5sIGMZWhRe\nXtgp327750hoWqZifBGk4vPGI9HTslKowI49zIGp0R3IF8k7yN1pfr478Gh4MpnE\nMoUBEbxHjB9gwjtTnAkkEedm1gRe5ZwTEFdcoUw7STmOayE6Wsc9RX8U/+iywRKq\nkzDunGKhJ9KIsh8jG4/zj0ckLhfkzEBW20CDk9q9nPZJNW3Mm0s+vhWde3xGqu9Q\n4tiW2LECgYEA/9c2HR8grXegelvNOeF6tC79CMOSSre9vbggLD/SLU1gWgPk3tza\nnvElRyvDcsHzYfs8gEb3/493xxooTxvak7QwMh+ciZHCXgWSUI5/bBs3mknFsSSL\nucsfxcELhljzDcdOAW4xGvbJr9vJ4OyS2UBXAbjaBQ1EYGrHiNVVnKUCgYEA2BVs\n4QbWiqS2Q5zq05Uvos2ppuUssqsF5ToZO2Zl1hc6jdnRG0vTx8sSrWvfG6ehgWrZ\n4xNyuFXiABKGFLepKSfmHv80TQKN2RV2N9dTgtXDoh/Iztnz1VnA+m4jUBblZyGn\nwok6DkiJVMo+WQ8vXBDV5kFJroft8yY+BVBGH3UCgYEA78vVAbiyVUUCGo2/LxhD\nfW1pZ/R/Qx8zbgaNyUvMgP+8ZsKtm6IgG8fk6+9+EyrtJ5JnY8ihHF1ppCnFTFjM\nJ5NFdUWh4GPJbX0FZhIaJsbf9/JbpKyfdnaIAj/twG/Q6MI9QCP7TM2xvu5gKz0y\nawTeSFPtrbyAsWqEOaHTy60CgYA2wjc1T2ZO/C60M6/Orp/DwhqcELejD3QPAwoh\n43ErL/fGuswi/rRMjUnOaOfBOlnTUiClSuhnjlwXaJpR5bkYlOPcNxAp89u+h5HN\n1ON05HcPPr7ErLb9+iDNVdvdD/BSklTRF7V+qSMkOZxTNWXrDtkl4KWrdQb391kA\nP7eFgQKBgB5hVR5mGCXiWFVhvaw1yeG+QNbag8CkcDdi/z4ABo1I4L2STbrW62Pa\nbDYfzTi4Oyp9YUM8IMAsC+6JiF2rOlHoVEPqYO/Iib929fbpoebvwJLWTZVRYPJ1\nD9qMtXDjj2Cz4xKqPMIwfu9Id7CfZKcB1Ah5fUGMQpmmbKvcTdv7\n-----END RSA PRIVATE KEY-----\n"
alipay_public_key: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApknNHN7lLvKb8pJ7IVxv\nmKiK1hudv/VryFpOTfdcyArCF+FUpqtI5K2v2K/Fo8EQFsdKJpXUTj10uD9k/6oA\nwFuB9VEDxu2ZxUY5VhDeSh5xizfmzNqeqQdRX76MsjQo3qvC0sRLL+3DMY7GfTjl\nGeVtr3mBybHGECXSNob9Qh2jTpr9BgyFGvJhnfvPuLJcf/myWsNN6RdC1hj2rUHs\nq1fkKG3j0tnOeYh+KKFX0x8CAkElGWY62oKWPZ9iEOdoM4cXvFv9MQ4lo/8y0FEi\nXlgiVaG7gvFV5RQG+ZL3C8qDf5xq3PGmPBPTljNaXWPY/6xYI4YdX/RWFaZuz5EJ\nVwIDAQAB\n-----END PUBLIC KEY-----\n"
