root_url: 'http://gesanghua.wikiflyer.cn/'
app_host: 'gesanghua.wikiflyer.cn'
app_name: '格桑花项目'
app_desc: '格桑花项目'
logo_img: ''

send_sms: 'true'

junior_term_amount: 1050
junior_year_amount: 2100
senior_term_amount: 1050
senior_year_amount: 2100
