:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:timeout: 3600
:queues:
  - [default, 10]

staging:
  :concurrency: 5
development:
  :concurrency: 5
production:
  :concurrency: 20
